"""empty message

Revision ID: 63aa4dc88fe1
Revises: e1b71a3a2efb
Create Date: 2025-07-10 08:08:22.995614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aa4dc88fe1'
down_revision = 'e1b71a3a2efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('customer_concern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_doc_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_doc_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('relationship_doc_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('group_join_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'stokvel_group', ['group_id'], ['id'])
        batch_op.drop_column('tier_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_join_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('amount')
        batch_op.drop_column('tier')
        batch_op.drop_column('category')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('relationship_doc_url')
        batch_op.drop_column('address_doc_url')
        batch_op.drop_column('id_doc_url')

    op.drop_table('savings_goal')
    op.drop_table('customer_concern')
    op.drop_table('market_transaction')
    # ### end Alembic commands ###
