"""empty message

Revision ID: eb9b67535dbf
Revises: 569b823bb5be
Create Date: 2025-07-03 11:13:04.134293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9b67535dbf'
down_revision = '569b823bb5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id_document_path', sa.String(length=200), nullable=True),
    sa.Column('death_certificate_path', sa.String(length=200), nullable=True),
    sa.Column('proof_of_residence_path', sa.String(length=200), nullable=True),
    sa.Column('additional_documents_path', sa.String(length=200), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('fraud_indicators', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim')
    # ### end Alembic commands ###
